version 0.2

phases:
    install:
        runtime-versions: 
            nodejs: 10
    pre_build:
        commands:
            - yarn        
    build:
        commands:
            - echo "this is working"
            - docker build .
            - env

        